steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=Dockerfile'
      - '--context=.'
      - '--destination=${_IMAGE_NAME}'
      - '--cache=true'
      - '--cache-ttl=168h'
